# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twep.City')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twep.City')),
                ('district', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.District')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twep.District')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.CharField(default=None, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('twitter_msg_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('screen_name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('reply_to_id_str', models.CharField(default=None, max_length=20, null=True)),
                ('categories_keywords', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('text_summary_title', models.CharField(default=None, max_length=40, null=True)),
                ('text_summary', models.TextField(default=None, null=True)),
                ('child', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.Tweet')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.Location')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='twep.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=200, unique=True)),
                ('blob_data', models.TextField(db_column='data', default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='timeline',
            name='children',
            field=models.ManyToManyField(default=None, related_name='apostles', to='twep.Tweet'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='first_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prophet', to='twep.Tweet'),
        ),
        migrations.AddField(
            model_name='location',
            name='sub_district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.SubDistrict'),
        ),
        migrations.AddField(
            model_name='keywordcategory',
            name='tweets',
            field=models.ManyToManyField(default=None, to='twep.Tweet'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.KeywordCategory'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='situation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.Timeline'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='tweets',
            field=models.ManyToManyField(default=None, to='twep.Tweet'),
        ),
    ]
