# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=200)),
                ('twitter_msg_id', models.CharField(max_length=20, unique=True)),
                ('screen_name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('reply_to', models.CharField(blank=True, max_length=20, null=True)),
                ('situation_status', models.CharField(max_length=200)),
            ],
        ),
    ]
