# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytweet',
            name='id',
        ),
        migrations.AlterField(
            model_name='mytweet',
            name='reply_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet'),
        ),
        migrations.AlterField(
            model_name='mytweet',
            name='twitter_msg_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
