# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0002_auto_20170422_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytweet',
            name='reply_to',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
