# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0003_auto_20170422_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='danger',
            new_name='danger_level',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='tweets',
        ),
        migrations.AddField(
            model_name='mytweet',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mytweet',
            name='situation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.Situation'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
    ]
