# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0004_auto_20170423_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytweet',
            old_name='reply_to',
            new_name='reply_to_id_str',
        ),
        migrations.AddField(
            model_name='mytweet',
            name='reply_to_object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet'),
        ),
    ]
