# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0005_auto_20170423_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytweet',
            name='child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet'),
        ),
        migrations.AlterField(
            model_name='mytweet',
            name='reply_to_object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='twep.MyTweet'),
        ),
    ]
