# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0006_auto_20170423_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytweet',
            old_name='reply_to_object',
            new_name='parent',
        ),
    ]
