# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0007_auto_20170423_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytweet',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='tweets',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='status',
            field=models.CharField(choices=[('RP', 'Reported'), ('IP', 'In Progress'), ('RS', 'Resolved'), ('U', 'Unknown')], default='U', max_length=20),
        ),
    ]
