# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0010_auto_20170424_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('word',)},
        ),
        migrations.AlterModelOptions(
            name='situation',
            options={'ordering': ('danger_level', 'status')},
        ),
    ]
