# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0011_auto_20170424_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situation',
            options={},
        ),
    ]
