# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0012_auto_20170424_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytweet',
            name='situation',
        ),
        migrations.AddField(
            model_name='situation',
            name='base_tweet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet', verbose_name='base_mytweet_id'),
        ),
    ]
