# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0013_auto_20170424_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='base_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet', verbose_name='base_mytweet_id'),
        ),
    ]
