# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0018_auto_20170424_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='tweets',
        ),
        migrations.AddField(
            model_name='mytweet',
            name='keyword',
            field=models.ManyToManyField(default=None, null=True, to='twep.Keyword'),
        ),
    ]
