# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0020_auto_20170424_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('V', 'Violation'), ('D', 'Danger'), ('L', 'Location'), ('S', 'Status'), ('H', 'Happy'), ('A', 'Actor'), ('U', 'Unknown')], default='U', max_length=200),
        ),
    ]
