# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0021_auto_20170424_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytweet',
            name='rts_created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
