# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0022_mytweet_rts_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.RemoveField(
            model_name='mytweet',
            name='rts_created_at',
        ),
        migrations.AlterField(
            model_name='mytweet',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
