# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0025_auto_20170425_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcategory',
            name='words',
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.KeywordCategory'),
        ),
    ]
