# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0026_auto_20170427_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytweet',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='tweets',
            field=models.ManyToManyField(default=None, null=True, to='twep.MyTweet'),
        ),
    ]
