# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0033_auto_20170502_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='children',
        ),
        migrations.AddField(
            model_name='situation',
            name='children',
            field=models.ManyToManyField(default=None, null=True, related_name='children', to='twep.MyTweet'),
        ),
    ]
