# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0034_auto_20170502_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='children',
            field=models.ManyToManyField(default=None, related_name='children', to='twep.MyTweet'),
        ),
    ]
