# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0036_situation_screen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('sub_district', models.CharField(max_length=200)),
            ],
        ),
    ]
