# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0040_auto_20170502_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='base_tweet',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='children',
        ),
        migrations.AddField(
            model_name='mytweet',
            name='situation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.Situation'),
        ),
    ]
