# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0041_auto_20170503_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytweet',
            name='situation',
        ),
        migrations.AddField(
            model_name='situation',
            name='first_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.MyTweet'),
        ),
    ]
