# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0044_auto_20170503_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='first_tweet_children',
        ),
        migrations.AddField(
            model_name='situation',
            name='children',
            field=models.ManyToManyField(default=None, related_name='children', to='twep.MyTweet'),
        ),
    ]
