# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0047_remove_situation_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='first_tweet',
        ),
    ]
