# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0050_auto_20170503_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=200)),
                ('blob_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
    ]
