# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0050_auto_20170503_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=200, unique=True)),
                ('blob_data', models.TextField(db_column='data', default=None, null=True)),
            ],
        ),
    ]
