# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0051_markdownblob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownblob',
            name='screen_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
