# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0053_auto_20170506_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='screen_name',
        ),
        migrations.AddField(
            model_name='situation',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twep.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
