# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twep', '0054_auto_20170506_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkdownBlob',
        ),
        migrations.AddField(
            model_name='user',
            name='blob_data',
            field=models.TextField(db_column='data', default=None, null=True),
        ),
    ]
